### PR TITLE
Added the Description For Tags

### PR DESCRIPTION
**Pull request by zain-awais-gs**
Added The Description for Tags

### CODE REVIEW

**Review by asad-u — APPROVED** [review]
LGTM

**Review by dsemenovsky — APPROVED** [review]

**Comment by fbrunel** [comment]
@zain-awais Thanks for the change. That was quite easy to do that after all.

**Comment by fbrunel** [comment]
@zain-awais @asad-u I didn't see any default value (like `NIL`) in this migration, is this something we need to worry about? cc @dsemenovsky

**Comment by dsemenovsky** [comment]
@fbrunel this is fine since the default values will be NULL in DB anyways. No need for the default value if we want it to be NULL.

**Comment by fbrunel** [comment]
@dsemenovsky Alright, no problem, I was just checking.

**Pull request merged**
